<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TestAutomationlogo</name>
   <tag></tag>
   <elementGuidId>98b54772-ae76-4437-ba35-5b33556bb4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/div/div/div/div[1]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div[1]/div[1]/div/div/div/div[1]/h1</value>
   </webElementProperties>
</WebElementEntity>
