<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TheSiteForTesting</name>
   <tag></tag>
   <elementGuidId>aefdc000-12ae-4c09-b9b6-a0a0a621d4cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user-content-%5Bthe-site-for-testing-is-here%5D(https%3A%2F%2Fbetestautomation.azurewebsites.net%2F)&quot;]/a[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user-content-%5Bthe-site-for-testing-is-here%5D(https%3A%2F%2Fbetestautomation.azurewebsites.net%2F)&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
